### PR TITLE
Use https for git clone

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
It will work out of the box

### CODE REVIEW

**Comment by fxn** [comment]
I never use HTTPS for my own repos.

**Comment by deivid-rodriguez** [comment]
ssh requires extra configuration so I thought this would make things easier for users of the repo.

**Comment by fxn** [comment]
But in the host, someone willing to patch can be assumed to have their GitHub setup in place.

I think this one is fine, but thanks!

**Comment by deivid-rodriguez** [comment]
Welcome! :+1:

**Pull request closed without merging**
