### PR TITLE
no network ubuntu vagrant virtual box issue

### PR DESCRIPTION
**Pull request by equivalent**
Running this repo  under Vagrant in  Ubuntu 14.04 + Virtual box  http://bit.ly/1d1qUlh

basically guest has no internet connection

### CODE REVIEW

**Comment by fxn** [comment]
Hey, thanks for the patch but I am not convinced about adding this comment.

I have never heard of this issue, and it has never been reported in this project. If someone occasionally has a networking issue, they need to resort either to the documentation of Vagrant or VirtualBox, or else Google the problem. But our *Vagrantfile* cannot be an aggregation of what-if configurations.

**Comment by equivalent** [comment]
ok cool, can I create rails-dev-box wiky entry on this at least ?

**Comment by fxn** [comment]
If this trivial *Vagrantfile* builds a VM without networking Vagrant or VirtualBox would be seriously broken. This can't be the case.

I prefer that people Google gotchas, honestly.

**Comment by equivalent** [comment]
ok cool

**Pull request closed without merging**
